### ISSUE TITLE
[wordpress.current.version] token not being replaced

### ISSUE THREAD

**Issue by uamv** [mainwp/mainwp-client-reports-extension#50]
I have been unsuccessful in getting the [wordpress.current.version] token to return the current WordPress version. Emailed reports and the generated PDF continue to show only the token.

The token does work when used with the [section.wordpress.updated] loop, but not as a stand-alone, which documentation appears to show it should.

**Comment by bogdan-mainwp** [comment]
Hi @uamv, my apologies for the late response here. 

`[wordpress.current.version]` is actually designed to work only inside the `[section.wordpress.updated]`. Documenation has been updated so it doesn't mislead users.

**Comment by uamv** [comment]
Thanks for the clarification. I did see now that, at least with Pro Reports, this information is available via the `[client.site.version]` token.
