### ISSUE TITLE
Plugin problem with generating reports

### ISSUE THREAD

**Issue by sakthiwebdev** [mainwp/mainwp-client-reports-extension#51]
MainWP Client Reports Extension - 4.0.3
Client Reports- 2.0.4

Problems

1. New updates have been made on the child website, but not reflecting on the reports. (i have synced the child website several time).

2. Reports showing the shortcodes ( Tokens - [backup.created.count] ) instead of the actual results for them. this is happening after the update from 4.0.0 -> 4.0.3

**Comment by kwcjr** [comment]
Would you mind opening a private [Help Desk ticket](https://mainwp.com/my-account/get-support/) so we can collect some additional information & investigate further?
